### ISSUE TITLE
请求增加RSS feed

### ISSUE THREAD

**Issue by heyeshuang** [Sterncat/sterncat.github.io#1]
Hi Sterncat,

我很喜欢您的博客，希望能够通过feedly订阅更新，但是其[RSS地址](https://faster-than-light.net/atom.xml)已经失效，不知您能否进行修正？

谢谢！

**Comment by Sterncat** [comment]
很高兴您喜欢这个blog，我生成了一下atom文件，在”联系我们“那里也增加了rss的按钮，请试一试好不好用，谢谢！

贺叶霜 ***@***.***> 于2021年7月24日周六 上午7:21写道：

**Comment by heyeshuang** [comment]
没问题了，谢谢~
